--DROP SECTION
DROP TABLE DETALLE_FACTURA CASCADE CONSTRAINTS;
DROP TABLE FACTURA CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE ARTICULO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE ZONA CASCADE CONSTRAINTS;

--SEQUENCE SECTION
DROP SEQUENCE SEQ_FACT_ID;
DROP SEQUENCE SEQ_ZONA_ID;
DROP SEQUENCE SEQ_CATEGORIA_ID;
DROP SEQUENCE SEQ_ARTICULO_ID;

CREATE SEQUENCE SEQ_FACT_ID
INCREMENT BY 10
START WITH 10000
MAXVALUE 999999;

CREATE SEQUENCE SEQ_ZONA_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 99;

CREATE SEQUENCE SEQ_CATEGORIA_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 99;

CREATE SEQUENCE SEQ_ARTICULO_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 999;

--SEQ_FACT_ID.nextval

--CREATE SECTION
CREATE TABLE ZONA (
    ID_ZONA NUMBER(2) NOT NULL,
    NOM_ZONA VARCHAR(10) NOT NULL,
    PORC NUMBER(5,2) NOT NULL,
    CONSTRAINT PK_ZONA PRIMARY KEY (ID_ZONA)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER(2) NOT NULL,
    NOM_CATEGORIA VARCHAR(20) NOT NULL,
    PORCENTAJE NUMBER(5,2) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE VENDEDOR (
    ID_VENDEDOR NUMBER(6) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1
    INCREMENT BY 1,
    RUT_VENDEDOR VARCHAR2(10) NOT NULL UNIQUE,
    NOMBRES_VENDEDOR VARCHAR2(25) NOT NULL,
    APPATERNO_VENDEDOR VARCHAR2(15) NOT NULL,
    APMATERNO_VENDEDOR VARCHAR2(15),
    FEC_NAC_VENDEDOR DATE NOT NULL,
    FEC_CONTR_VENDEDOR DATE NOT NULL,
    SUELDO NUMBER NOT NULL,
    COMISION NUMBER NOT NULL,
    ID_ZONA NUMBER(1),
    ID_CATEGORIA NUMBER(1) NOT NULL,
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID_VENDEDOR),
    CONSTRAINT FK_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    CONSTRAINT FK_ZONA FOREIGN KEY (ID_ZONA) REFERENCES ZONA(ID_ZONA)
);

CREATE TABLE MARCA (
    ID_MARCA NUMBER(4) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1000
    START WITH 1000
    INCREMENT BY 100,
    NOM_MARCA VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA)
);

CREATE TABLE ARTICULO (
    ID_ARTICULO NUMBER(3) NOT NULL,
    NOM_ARTICULO VARCHAR2(25) NOT NULL,
    PRECIO NUMBER(9) NOT NULL,
    STOCK_ACTUAL NUMBER(4) NOT NULL,
    STOCK_MINIMO NUMBER(4) NOT NULL,
    ID_MARCA NUMBER(4) NOT NULL,
    CONSTRAINT CHK_STOCKS CHECK (STOCK_ACTUAL >= STOCK_MINIMO),
    CONSTRAINT PK_ARTICULO PRIMARY KEY (ID_ARTICULO),
    CONSTRAINT FK_MARCA FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA)
);

CREATE TABLE COMUNA (
    ID_COMUNA NUMBER(3) GENERATED ALWAYS AS IDENTITY
    MINVALUE 100
    START WITH 100
    INCREMENT BY 5,
    NOM_COMUNA VARCHAR2(60) NOT NULL,
    CONSTRAINT PK_COMUNA PRIMARY KEY (ID_COMUNA)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(6) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1
    INCREMENT BY 1,
    NOMBRE_CLIENTE VARCHAR2(35) NOT NULL,
    DIRECCION_CLIENTE VARCHAR2(50) NOT NULL,
    TELEFONO_CLIENTE VARCHAR2(15) NOT NULL,
    ID_COMUNA NUMBER(3) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE),
    CONSTRAINT FK_COMUNA FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA)
);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER(6) NOT NULL,
    ID_CLIENTE NUMBER(6) NOT NULL,
    ID_VENDEDOR NUMBER(6) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACTURA),
    CONSTRAINT FK_CLIENTE_FACT FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_VENDEDOR_FACT FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR)
);

CREATE TABLE DETALLE_FACTURA (
    ID_FACTURA NUMBER(6) NOT NULL,
    ID_ARTICULO NUMBER(2) NOT NULL,
    CANTIDAD VARCHAR2(6) NOT NULL,
    CONSTRAINT PK_DET_FACTURA PRIMARY KEY (ID_FACTURA, ID_ARTICULO),
    CONSTRAINT FK_DET_FACT FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
    CONSTRAINT FK_DET_ART FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO(ID_ARTICULO)
);


--INSERT SECTION

INSERT INTO COMUNA(NOM_COMUNA)
VALUES       ('PROVIDENCIA');
INSERT INTO COMUNA(NOM_COMUNA)
VALUES       ('SANTIAGO');
INSERT INTO COMUNA(NOM_COMUNA)
VALUES       ('ÑUÑOA');
INSERT INTO COMUNA(NOM_COMUNA)
VALUES       ('LA FLORIDA');
INSERT INTO COMUNA(NOM_COMUNA)
VALUES       ('MAIPU');

INSERT INTO MARCA(NOM_MARCA)
VALUES       ('FAMILAND');
INSERT INTO MARCA(NOM_MARCA)
VALUES       ('NIVEA');
INSERT INTO MARCA(NOM_MARCA)
VALUES       ('DOVE');
INSERT INTO MARCA(NOM_MARCA)
VALUES       ('GILLETE');
INSERT INTO MARCA(NOM_MARCA)
VALUES       ('MONTERREY');

INSERT INTO CATEGORIA(ID_CATEGORIA, NOM_CATEGORIA, PORCENTAJE)
VALUES       (SEQ_CATEGORIA_ID.nextval, 'CATEGORIA A', '17,5');
INSERT INTO CATEGORIA(ID_CATEGORIA, NOM_CATEGORIA, PORCENTAJE)
VALUES       (SEQ_CATEGORIA_ID.nextval, 'CATEGORIA B', '12,6');
INSERT INTO CATEGORIA(ID_CATEGORIA, NOM_CATEGORIA, PORCENTAJE)
VALUES       (SEQ_CATEGORIA_ID.nextval, 'CATEGORIA C', '9,4');
INSERT INTO CATEGORIA(ID_CATEGORIA, NOM_CATEGORIA, PORCENTAJE)
VALUES       (SEQ_CATEGORIA_ID.nextval, 'CATEGORIA D', '7,2');
INSERT INTO CATEGORIA(ID_CATEGORIA, NOM_CATEGORIA, PORCENTAJE)
VALUES       (SEQ_CATEGORIA_ID.nextval, 'CATEGORIA E', '5,4');

INSERT INTO ZONA(ID_ZONA, NOM_ZONA, PORC)
VALUES      (SEQ_ZONA_ID.nextval, 'NORTE', '8,56');
INSERT INTO ZONA(ID_ZONA, NOM_ZONA, PORC)
VALUES       (SEQ_ZONA_ID.nextval, 'SUR', '10,48');
INSERT INTO ZONA(ID_ZONA, NOM_ZONA, PORC)
VALUES       (SEQ_ZONA_ID.nextval, 'ORIENTE', '11,27');
INSERT INTO ZONA(ID_ZONA, NOM_ZONA, PORC)
VALUES       (SEQ_ZONA_ID.nextval, 'PONIENTE', '7,24');
INSERT INTO ZONA(ID_ZONA, NOM_ZONA, PORC)
VALUES       (SEQ_ZONA_ID.nextval, 'CENTRO', '7,24');

INSERT INTO CLIENTE(NOMBRE_CLIENTE,DIRECCION_CLIENTE,TELEFONO_CLIENTE,ID_COMUNA)
VALUES       ('ALCARAZ NOVOA MONTSERRAT','BUENAVENTURA 160', '564522114','100');
INSERT INTO CLIENTE(NOMBRE_CLIENTE,DIRECCION_CLIENTE,TELEFONO_CLIENTE,ID_COMUNA)
VALUES       ('JIMENEZ LORCA ELENA','LAGUNAS 52 DEPTO. K', '566665443','105');
INSERT INTO CLIENTE(NOMBRE_CLIENTE,DIRECCION_CLIENTE,TELEFONO_CLIENTE,ID_COMUNA)
VALUES       ('TORRES ROCA MARIA','DONATELLO 7421', '565626134','115');
INSERT INTO CLIENTE(NOMBRE_CLIENTE,DIRECCION_CLIENTE,TELEFONO_CLIENTE,ID_COMUNA)
VALUES       ('LOPEZ ROJAS THOMAS','ORDOÑEZ 2007', '562989233','120');
INSERT INTO CLIENTE(NOMBRE_CLIENTE,DIRECCION_CLIENTE,TELEFONO_CLIENTE,ID_COMUNA)
VALUES       ('ZAMORA MOLINA TOMAS','HUERFANOS 1294', '564343456','105');

INSERT INTO ARTICULO(ID_ARTICULO,NOM_ARTICULO,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_MARCA)
VALUES      (SEQ_ARTICULO_ID.nextval,'JABON','1250','150','80','1000');
INSERT INTO ARTICULO(ID_ARTICULO,NOM_ARTICULO,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_MARCA)
VALUES      (SEQ_ARTICULO_ID.nextval,'SHAMPOO','2325','50','20','1200');
INSERT INTO ARTICULO(ID_ARTICULO,NOM_ARTICULO,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_MARCA)
VALUES      (SEQ_ARTICULO_ID.nextval,'ACONDICIONADOR','2100','200','50','1200');
INSERT INTO ARTICULO(ID_ARTICULO,NOM_ARTICULO,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_MARCA)
VALUES      (SEQ_ARTICULO_ID.nextval,'CREMA DE AFEITAR','3475','50','20','1300');
INSERT INTO ARTICULO(ID_ARTICULO,NOM_ARTICULO,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_MARCA)
VALUES      (SEQ_ARTICULO_ID.nextval,'CAFE','3500','80','40','1400');

INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,APMATERNO_VENDEDOR,FEC_NAC_VENDEDOR,FEC_CONTR_VENDEDOR,SUELDO,COMISION,ID_ZONA,ID_CATEGORIA)
VALUES      ('11111112-6','BENITO','ORDENES','ROMERO','22/05/63','16/04/85','350000','0,13','1','3');
INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,FEC_NAC_VENDEDOR,FEC_CONTR_VENDEDOR,SUELDO,COMISION,ID_ZONA,ID_CATEGORIA)
VALUES      ('12222222-3','MARTA','VIVEROS','07/08/78','02/07/00','345000','0,07','2','2');
INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,APMATERNO_VENDEDOR,FEC_NAC_VENDEDOR,FEC_CONTR_VENDEDOR,SUELDO,COMISION,ID_ZONA,ID_CATEGORIA)
VALUES      ('13333333-K','OSCAR','CACERES','LAGOS','09/10/79','03/09/01','367400','0,13','1','1');
INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,APMATERNO_VENDEDOR,FEC_NAC_VENDEDOR,FEC_CONTR_VENDEDOR,SUELDO,COMISION,ID_ZONA,ID_CATEGORIA)
VALUES      ('14444444-5','MILENA','MENA','CARTES','08/12/77','03/11/99','373620','0,05','3','3');
INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,FEC_NAC_VENDEDOR,FEC_CONTR_VENDEDOR,SUELDO,COMISION,ID_CATEGORIA)
VALUES      ('15555555-6','ESTEBAN','ROMERO','08/12/88','03/11/15','373620','0,08','3');

INSERT INTO FACTURA(ID_FACTURA,ID_CLIENTE,ID_VENDEDOR)
VALUES      (SEQ_FACT_ID.nextval,'1','2');
INSERT INTO FACTURA(ID_FACTURA,ID_CLIENTE,ID_VENDEDOR)
VALUES      (SEQ_FACT_ID.nextval,'2','4');
INSERT INTO FACTURA(ID_FACTURA,ID_CLIENTE,ID_VENDEDOR)
VALUES      (SEQ_FACT_ID.nextval,'4','3');
INSERT INTO FACTURA(ID_FACTURA,ID_CLIENTE,ID_VENDEDOR)
VALUES      (SEQ_FACT_ID.nextval,'3','5');
INSERT INTO FACTURA(ID_FACTURA,ID_CLIENTE,ID_VENDEDOR)
VALUES      (SEQ_FACT_ID.nextval,'2','2');

INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10000','1','20');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10000','5','23');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10010','3','38');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10010','4','43');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10010','1','48');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10020','4','30');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10020','2','20');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10030','5','60');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10030','2','45');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10030','3','35');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10040','4','29');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10040','5','28');
INSERT INTO DETALLE_FACTURA(ID_FACTURA,ID_ARTICULO,CANTIDAD)
VALUES      ('10040','2','21');
