--DROP SECTION
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;

--DROP SEQUENCE SECTION
DROP SEQUENCE SEQ_ID;

--SEQUENCE SECTION
CREATE SEQUENCE SEQ_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 999999;

--CREATE SECTION
CREATE TABLE VENDEDOR (
    ID_VENDEDOR NUMBER(6) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 999999
    START WITH 1
    INCREMENT BY 1, --AUTOINCREMENTAL
    RUT_VENDEDOR VARCHAR2(10) NOT NULL UNIQUE, --VALOR UNICO
    NOMBRES_VENDEDOR VARCHAR2(25) NOT NULL,
    APPATERNO_VENDEDOR VARCHAR2(15) NOT NULL,
    APMATERNO_VENDEDOR VARCHAR2(15), --OPCIONAL
    FEC_NAC_VENDEDOR DATE NOT NULL,
    SUELDO NUMBER NOT NULL,
    SUELDO_MINIMO NUMBER,
    ID_ZONA NUMBER(1), --ALMACENA FOREIGN KEY
    INDEFINIDO VARCHAR2(5) NOT NULL,
    CONSTRAINT CK_INDEFINIDO CHECK (INDEFINIDO IN ('TRUE', 'FALSE')), --CHECK TRUE OR FALSE
    CONSTRAINT PK_VENDEDOR PRIMARY KEY (ID_VENDEDOR), --PRIMARY KEY
    CONSTRAINT FK_ZONA FOREIGN KEY (ID_ZONA) REFERENCES ZONA(ID_ZONA) --FOREIGN KEY
    CONSTRAINT CHK_SUELDO CHECK (SUELDO >= SUELDO_MINIMO) --CHECK SUELDO DEBE SER MAYOR QUE SUELDO_MINIMO
);

--INSERT SECTION
INSERT INTO VENDEDOR(RUT_VENDEDOR,NOMBRES_VENDEDOR,APPATERNO_VENDEDOR,APMATERNO_VENDEDOR,FEC_NAC_VENDEDOR,SUELDO,ID_ZONA,INDEFINIDO)
VALUES      ('11111112-6','BENITO','ORDENES','ROMERO','22/05/63','350000','1','TRUE');
--SEQ_ID.nextval PARA USAR SECUENCIA