DROP TABLE ACOMPANANTE CASCADE CONSTRAINT;
DROP TABLE ANULAR_RESERVA CASCADE CONSTRAINT;
DROP TABLE BANCO CASCADE CONSTRAINT;
DROP TABLE CABANA CASCADE CONSTRAINT;
DROP TABLE CLIENTE CASCADE CONSTRAINT;
DROP TABLE COMUNA CASCADE CONSTRAINT;
DROP TABLE CONTRATACION_SERVICIO CASCADE CONSTRAINT;
DROP TABLE CUENTA CASCADE CONSTRAINT;
DROP TABLE DESCUENTO CASCADE CONSTRAINT;
DROP TABLE DOMO CASCADE CONSTRAINT;
DROP TABLE HABITACION CASCADE CONSTRAINT;
DROP TABLE REGION CASCADE CONSTRAINT;
DROP TABLE RESERVA CASCADE CONSTRAINT;
DROP TABLE SERVICIOS CASCADE CONSTRAINT;

CREATE TABLE REGION (
    ID_REGION NUMBER(3) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 999
    START WITH 1
    INCREMENT BY 1,
    NOMBRE_REGION VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (ID_REGION)
);

CREATE TABLE COMUNA (
    ID_COMUNA NUMBER(3) PRIMARY KEY,
    NOMBRE_COMUNA VARCHAR2(20) NOT NULL,
    REGION NUMBER(20) NOT NULL,
    FOREIGN KEY (REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE ACOMPANANTE(
    ID_ACOMPANANTE NUMBER(3) PRIMARY KEY,
    RUN_ACOMPANANTE VARCHAR2(10) NOT NULL,
    FONO_ACOMPANANTE NUMBER(12) NOT NULL,
    NOMBRE_COMPLETO VARCHAR2(32) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER(5) PRIMARY KEY,
    RUN VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(10) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(10) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(10) NOT NULL,
    CORREO VARCHAR2(10) NOT NULL,
    FONO NUMBER(12) NOT NULL,
    DIRECCION VARCHAR2(20) NOT NULL,
    ID_COMUNA NUMBER(20) NOT NULL,
    ID_ACOMPANANTE NUMBER(3) NOT NULL,
    FOREIGN KEY (ID_COMUNA) REFERENCES COMUNA(ID_COMUNA),
    FOREIGN KEY (ID_ACOMPANANTE) REFERENCES ACOMPANANTE(ID_ACOMPANANTE)
);

CREATE TABLE CABANA (
    ID_CABANA NUMBER(5) PRIMARY KEY,
    CANTIDAD_DORMITORIOS NUMBER(2) NOT NULL,
    CANTIDAD_BANOS NUMBER(1) NOT NULL,
    CANTIDAD_COCINA NUMBER(1) NOT NULL,
    CANTIDAD_TINAJAS NUMBER(1) NOT NULL
);

CREATE TABLE DOMO (
    ID_DOMO NUMBER(5) PRIMARY KEY,
    MINIBAR VARCHAR2(5) NOT NULL,
    CONSTRAINT CK_MINIBAR CHECK (MINIBAR IN ('TRUE', 'FALSE')),
    BANO_PRIVADO VARCHAR2(5) NOT NULL,
    CONSTRAINT CK_BANO_PRIVADO CHECK (BANO_PRIVADO IN ('TRUE', 'FALSE')),
    CALEFACCION VARCHAR2(5) NOT NULL,
    CONSTRAINT CK_CALEFACCION CHECK (CALEFACCION IN ('TRUE', 'FALSE')),
    CANTIDAD_CAMAS NUMBER(2) NOT NULL
);

CREATE TABLE HABITACION (
    NUMERO_HABITACION NUMBER(5) PRIMARY KEY,
    VALOR_NOCHE NUMBER(9) NOT NULL,
    CANT_MAX_PERSONAS NUMBER(2) NOT NULL,
    ID_CABANA NUMBER(5) NOT NULL,
    ID_DOMO NUMBER(5) NOT NULL,
    FOREIGN KEY (ID_CABANA) REFERENCES CABANA(ID_CABANA),
    FOREIGN KEY (ID_DOMO) REFERENCES DOMO(ID_DOMO)
);

CREATE TABLE DESCUENTO (
    CODIGO NUMBER(10) PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL,
    PORCENTAJE_DESCUENTO NUMBER(3) NOT NULL
);

CREATE TABLE SERVICIOS (
    CODIGO NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(15) NOT NULL,
    DESCRIPCION VARCHAR2(30) NOT NULL,
    PRECIO_POR_PERSONA VARCHAR2(9) NOT NULL
);

CREATE TABLE BANCO (
    ID_BANCO NUMBER(9) PRIMARY KEY,
    NOMBRE_BANCO VARCHAR2(15) NOT NULL
);

CREATE TABLE CUENTA (
    NUMERO_CUENTA NUMBER(15) PRIMARY KEY,
    TIPO_CUENTA VARCHAR2(10) NOT NULL,
    ID_BANCO NUMBER(9) NOT NULL,
    FOREIGN KEY (ID_BANCO) REFERENCES BANCO(ID_BANCO)
);

CREATE TABLE ANULAR_RESERVA(
    ID_ANULACION NUMBER(10) PRIMARY KEY,
    FECHA_ANULACION DATE NOT NULL,
    MONTO_PAGADO NUMBER(9) NOT NULL,
    MOTIVO_ANULACION VARCHAR2(1000) NOT NULL,
    DETALLE_ANULACION VARCHAR2(20) NOT NULL,
    NUMERO_CUENTA NUMBER(15) NOT NULL,
    FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTA(NUMERO_CUENTA)
);

CREATE TABLE RESERVA (
    NUMERO NUMBER(10) PRIMARY KEY,
    FECHA_RESERVA DATE NOT NULL,
    FECHA_CHECK_IN DATE NOT NULL,
    FECHA_CHECK_OUT DATE NOT NULL,
    PAGO_SIN_DESCUENTO NUMBER(9) NOT NULL,
    VALOR_DESCUENTO NUMBER(3) NOT NULL,
    PAGO_DESCUENTO NUMBER(9) NOT NULL,
    FECHA_CONTRATACION_SERVICIO DATE NOT NULL,
    ID_CLIENTE NUMBER(5) NOT NULL,
    NUMERO_HABITACION NUMBER(5) NOT NULL,
    DESCUENTO NUMBER(10) NOT NULL,
    ANULACION NUMBER(10),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (NUMERO_HABITACION) REFERENCES HABITACION(NUMERO_HABITACION),
    FOREIGN KEY (DESCUENTO) REFERENCES DESCUENTO(CODIGO),
    FOREIGN KEY (ANULACION) REFERENCES ANULAR_RESERVA(ID_ANULACION)
);

CREATE TABLE CONTRATACION_SERVICIO (
    FECHA_CONTRATACION DATE NOT NULL,
    ID_RESERVA NUMBER(10) NOT NULL,
    ID_SERVICIO NUMBER(10) NOT NULL,
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVA(NUMERO),
    FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIOS(CODIGO)
);

INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('ARICA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('TARAPACA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('ANTOFAGASTA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('ATACAMA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('COQUIMBO');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('VALPARAISO');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('METROPOLITANA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('OHIGGINS');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('MAULE');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('ÑUBLE');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('BIOBIO');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('ARAUCANIA');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('LOS RIOS');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('LOS LAGOS');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('AYSEN');
INSERT INTO REGION (NOMBRE_REGION) 
VALUES             ('MAGALLANES');


/*
CREATE SEQUENCE SEQ_REG_ID
INCREMENT BY 1
START WITH 1
MAXVALUE 20;


INSERT INTO REGION (ID_REGION, NOMBRE_REGION) 
VALUES             (SEQ_REG_ID.NEXTVAL, 'ARICA');
INSERT INTO REGION (ID_REGION, NOMBRE_REGION) 
VALUES             (SEQ_REG_ID.NEXTVAL, 'ANTOFAGASTA');
*/