DROP TABLE TIPO_EMPLEADO CASCADE CONSTRAINT;
DROP TABLE EMPLEADO CASCADE CONSTRAINT;
DROP TABLE VENTAS CASCADE CONSTRAINT;
DROP TABLE COMISION_VENTAS CASCADE CONSTRAINT;

CREATE TABLE TIPO_EMPLEADO (
    TIPO_EMPLEADO NUMBER(2) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99
    START WITH 1
    INCREMENT BY 1,
    DESC_TIPO_EMPLEADO VARCHAR2(25) NOT NULL,
    CONSTRAINT PK_TIPO_EMPLEADO PRIMARY KEY (TIPO_EMPLEADO)
);

CREATE TABLE EMPLEADO (
    ID_EMPLEADO NUMBER(5) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99999
    START WITH 1
    INCREMENT BY 2,
    NUMRUT NUMBER(10) NOT NULL UNIQUE,
    DVRUT NUMBER(1) NOT NULL,
    PRIMER_NOMBRE VARCHAR2(20) NOT NULL,
    SNOMBRE VARCHAR2(20),
    APPATERNO VARCHAR2(20) NOT NULL,
    APMATERNO VARCHAR2(20) NOT NULL,
    FECHA_CONTRATO DATE NOT NULL,
    TIPO_EMPLEADO NUMBER(2) NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO)
);

ALTER TABLE EMPLEADO 
ADD CONSTRAINT FK_TIPO_EMPLEADO FOREIGN KEY (TIPO_EMPLEADO) REFERENCES TIPO_EMPLEADO(TIPO_EMPLEADO);

CREATE TABLE VENTAS (
    NRO_BOLETA NUMBER(8) GENERATED ALWAYS AS IDENTITY
    MINVALUE 1
    MAXVALUE 99999999
    START WITH 1
    INCREMENT BY 3,
    ID_EMPLEADO NUMBER(5) NOT NULL,
    FECHA_BOLETA DATE NOT NULL,
    MONTO_TOTAL NUMBER(8) NOT NULL,
    CONSTRAINT PK_VENTAS PRIMARY KEY (NRO_BOLETA)
);

ALTER TABLE VENTAS
ADD CONSTRAINT FK_TE_VENTAS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO);

CREATE TABLE COMISION_VENTAS (
    NRO_BOLETA NUMBER(5) NOT NULL,
    MONTO_COMISION NUMBER(8) NOT NULL,
    FOREIGN KEY (NRO_BOLETA) REFERENCES VENTAS(NRO_BOLETA),
    CONSTRAINT PK_COMISION_VENTAS PRIMARY KEY (NRO_BOLETA)
);

INSERT INTO TIPO_EMPLEADO (DESC_TIPO_EMPLEADO)
VALUES              ('OPERARIO');
INSERT INTO TIPO_EMPLEADO (DESC_TIPO_EMPLEADO)
VALUES              ('SUPERVISOR');
INSERT INTO TIPO_EMPLEADO (DESC_TIPO_EMPLEADO)
VALUES              ('ENCARGADO');

/*
INSERT INTO EMPLEADO (NUMRUT, DVRUT, PRIMER_NOMBRE,SNOMBRE,APPATERNO,APMATERNO,FECHA_CONTRATO,TIPO_EMPLEADO) 
VALUES             ('19033095','8','Rodrigo','Esteban','Lopez','Garrido','01/05/2021','1');
INSERT INTO EMPLEADO (NUMRUT, DVRUT, PRIMER_NOMBRE,SNOMBRE,APPATERNO,APMATERNO,FECHA_CONTRATO,TIPO_EMPLEADO) 
VALUES             ('16758412','8','Eustacio','Narciso','Gomez','Perez','01/01/2020','2');
INSERT INTO EMPLEADO (NUMRUT, DVRUT, PRIMER_NOMBRE,SNOMBRE,APPATERNO,APMATERNO,FECHA_CONTRATO,TIPO_EMPLEADO) 
VALUES             ('10712536','8','Natalia','Sofia','Perez','Gonzalez','01/07/2022','3');

INSERT INTO VENTAS (ID_EMPLEADO,FECHA_BOLETA,MONTO_TOTAL)
VALUES              ('1','05/05/2023','55000');
INSERT INTO VENTAS (ID_EMPLEADO,FECHA_BOLETA,MONTO_TOTAL)
VALUES              ('1','06/05/2023','78000');
INSERT INTO VENTAS (ID_EMPLEADO,FECHA_BOLETA,MONTO_TOTAL)
VALUES              ('3','07/05/2023','118000');

INSERT INTO COMISION_VENTAS (NRO_BOLETA,MONTO_COMISION)
VALUES              ('1','5500');
INSERT INTO COMISION_VENTAS (NRO_BOLETA,MONTO_COMISION)
VALUES              ('4','7800');
INSERT INTO COMISION_VENTAS (NRO_BOLETA,MONTO_COMISION)
VALUES              ('7','11800');
*/

--CREATE SEQ

--EMPLEADO AUTOINCREMENTAL 2 EN 2
--TIPO_EMPLEADO AUTOINCREMENTAL 1 EN 1
--VENTAS AUTOINCREMENTAL 3 EN 3
--COMISION_VENTAS AUTOINCREMENTAL 4 EN 4
